### ISSUE TITLE
Can not use methods as described.

### ISSUE THREAD

**Issue by modi28** [froala/angular-froala#64]
I get this error in console:
TypeError: $scope.froalaOptions.froalaEditor is not a function
      $scope.froalaOptions is working fine.

My Code:

      $scope.froalaOptions = {
                toolbarBottom: true,
                charCounterCount: false,
                toolbarButtons: ["bold", "italic", "underline"]

            };
            $scope.froalaOptions.froalaEditor("selection.get");

**Comment by cgallarno** [comment]
Hey @modi28 it seems that froalaEditor is getting accessed before it's initialized.

There are a couple of ways to solve this. You can watch `froalaOptions` for `froalaEditor` to be set, or use angular's $timeout.

### $timeout
```javascript
	myApp.controller('mainController', function($scope, $timeout) {

		$scope.froalaOptions = {
			placeholderText : 'Add a Title',
			charCounterCount: false,
			toolbarInline: true
		};

		$timeout(function () {
			$scope. froalaOptions.froalaEditor('events.focus');
		});

	});
```
--

### $watch
```javascript
var unwatch =  $scope.$watch('froalaOptions', function (nv, ov) {
	if (nv.hasOwnProperty('froalaEditor')){
        unwatch(); //De-register the watcher
		nv.froalaEditor('events.focus');
	}
});
```

I can look into possible methods to use the editor immediately after declaration.

**Comment by stefanneculai** [comment]
If you want to do something immediately after initialization, then you should do that inside the [initialized](https://www.froala.com/wysiwyg-editor/docs/events#initialized) event.

**Comment by cgallarno** [comment]
@stefanneculai I looked into that, and eventhough the event does get called the property in angular's $scope still isn't set, however the editor could be passed into the callback and used that way.

**Comment by stefanneculai** [comment]
The event should be set somehow before doing the editor intialization in order to make sure it will be triggered correctly.

**Comment by cgallarno** [comment]
Events and their callbacks are defined before the editor initializes, just the initialization event occurs before angular-froala assigns the editor's instance into a scope where someone's angular code can access. This usually isn't a problem, I assume, because running a method on the editor usually is the result of a button click that occurs far after the initialization happens so this isn't an issue.

To be clear this is something that should be fixed, but there are reasonable workarounds presented here until it gets patched.

**Comment by modi28** [comment]
Hi @cgallarno  @stefanneculai  Thanks for your time.

I am still getting same error, with $timeout and $watch both.

froalaOptions are working fine with me, And binding is working fine too.

**Comment by cgallarno** [comment]
@modi28 Can you access froalaEditor inside of a function that is called from ng-click?

**Comment by stefanneculai** [comment]
See the new Readme for using methods: https://github.com/froala/angular-froala#methods.
